"""Bundled WoW realm lists per region, for the name-lookup realm dropdown.

Generated by `scripts/fetch_realms.py` from the Blizzard Realm Index and
bundled (not fetched at runtime) so the lookup form renders instantly and
works for the majority of users who have no Blizzard creds. Each realm carries
its *real* Blizzard slug — naive slugification of the display name is wrong for
special-char realms (`Drak'Tharon` → `draktharon`), which would 404 on lookup.
"""

from __future__ import annotations

from functools import lru_cache

import yaml

from simf.core.constants import DATA_DIR

_REALMS_PATH = DATA_DIR / "realms.yaml"


@lru_cache(maxsize=1)
def _load() -> dict[str, list[tuple[str, str]]]:
    raw = yaml.safe_load(_REALMS_PATH.read_text()) or {}
    return {region: [(n, s) for n, s in pairs] for region, pairs in raw.items()}


@lru_cache(maxsize=8)
def _slug_map(region: str) -> dict[str, str]:
    return {name: slug for name, slug in _load().get(region, [])}


def realm_names(region: str) -> list[str]:
    """Sorted realm display names for a region; ``[]`` for an unknown region."""
    return [name for name, _slug in _load().get(region, [])]


def slug_for(region: str, name: str | None) -> str | None:
    """Blizzard slug for a realm display name in a region.

    Returns ``None`` for a blank name or one not in the bundled list (e.g. a
    free-typed custom realm) — callers fall back to slugifying the raw input.
    """
    if not name:
        return None
    return _slug_map(region).get(name)
