"""List or remove stale loop-managed git worktrees under ``.worktrees/``.

Hygiene tool for the autonomous loop. Each iteration of the loop spawns
a subagent inside a `.worktrees/agent-*` checkout, locks it, and
is supposed to release it on exit. In practice the auto-cleanup hasn't
been firing, so the harness accumulates 20+ locked worktrees over time
and disk + ref tables compound. This script:

  1. Parses ``git worktree list --porcelain`` to enumerate every
     registered worktree (locked or not, branch or detached).
  2. Classifies each one as STALE / KEEP using:
       - path lives under ``.worktrees/`` (not a user working tree);
       - is not the worktree the script is being invoked from (the running
         iteration);
       - has no uncommitted/untracked changes EXCLUDING the ignore-paths
         allowlist (``.venv``, ``__pycache__``, etc. — environment churn
         the loop doesn't own);
       - HEAD commit is "merged" — either reachable from ``origin/master``
         OR its branch had a PR that was merged (squash-merge case, where
         the original tip is no longer an ancestor of master);
       - filesystem mtime is at least ``--age`` hours old (default 4h),
         so an in-flight iteration is never disturbed.
  3. Reports STALE candidates. With ``--delete``, runs
     ``git worktree unlock`` + ``git worktree remove`` + (optionally)
     ``git branch -D`` for the local feature ref if it matches the
     loop's ``worktree-agent-*`` pattern.

Safety brakes:
  - Dry-run is the default. ``--delete`` must be passed explicitly.
  - The classifier is conservative: any branch whose HEAD is NOT
    reachable from master AND has no merged PR is KEPT, regardless of
    age, even on a ``worktree-agent-*`` branch.
  - The current worktree (resolved real path) is always KEPT.
  - Paths outside ``.worktrees/`` are always KEPT — this is the
    hard guard against ever touching the user's bare/main checkout.
  - The ignore-paths allowlist defaults to environment churn only
    (``.venv``, ``__pycache__``, ``.pytest_cache``, ``node_modules``,
    ``loop-summary.md``) — actual source-file changes (``M ``
    status, untracked Python files, etc.) still block deletion.

Invocation:

  python scripts/cleanup_stale_worktrees.py                # dry-run
  python scripts/cleanup_stale_worktrees.py --age 1        # 1-hour staleness
  python scripts/cleanup_stale_worktrees.py --delete       # apply

The script is a sibling of ``prune_merged_branches.py``; same shape,
same conservative default. See ``docs/feedback_parallel_agent_branch_hygiene.md``
for the historical reason the loop holds these locks so cautiously.

PR-merge fallback uses the GitHub REST API with a PAT read from
``~/.config/gh/token`` (same flow as ``docs/gh_pat_via_curl.md``).
If the token isn't present, the script falls back to ancestry-only
classification and prints a one-line note.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

# Worktrees under this prefix (relative to the repo root) are loop-managed
# scratch checkouts. Anything outside this prefix is the user's own work
# and is always protected.
LOOP_WORKTREE_PREFIX = ".worktrees/"

# Local branches named like this are auto-generated by the loop harness.
# We delete the ref after removing the worktree because nothing else will.
# Non-matching branches (feat/foo, etc.) are left alone — the user or
# ``prune_merged_branches.py`` owns those.
LOOP_BRANCH_PATTERN = re.compile(r"^worktree-agent-[0-9a-f]+$")

# Paths that are environment-churn rather than user work. When the only
# untracked entries in a worktree match these, the worktree is still
# considered clean for the purposes of safe deletion. Each entry is a
# basename (matched against the first path segment of `git status` lines)
# or a path with a trailing slash for directory matches. The defaults
# cover Python venv + caches and the loop's own status file.
DEFAULT_IGNORE_PATHS: frozenset[str] = frozenset(
    {
        ".venv/",
        "venv/",
        "__pycache__/",
        ".pytest_cache/",
        ".ruff_cache/",
        "node_modules/",
        ".coverage",
        "loop-summary.md",
        "loop-blocked.log",
        "loop-progress.log",
    }
)

REPO_OWNER = "ainestal"
REPO_NAME = "simf"
API_ROOT = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}"
DEFAULT_TOKEN_PATH = Path.home() / ".config" / "gh" / "token"


@dataclass(frozen=True)
class Worktree:
    """One entry parsed out of ``git worktree list --porcelain``.

    ``branch`` is the short branch name (without ``refs/heads/``) or
    ``None`` for detached HEADs. ``locked`` mirrors the porcelain
    ``locked`` line — informational only; we unlock before remove.
    """

    path: str
    head: str | None
    branch: str | None
    detached: bool
    locked: bool


@dataclass
class Classification:
    """Decision for one worktree. ``stale`` is the single source of truth.

    ``reason`` is a human-readable explanation that survives into the
    dry-run report so the user can audit WHY a worktree was flagged
    (or skipped).
    """

    worktree: Worktree
    stale: bool
    reason: str
    age_hours: float | None = None
    has_local_changes: bool = False
    branch_merged: bool | None = None  # None for detached + no ancestry check done
    extra: dict = field(default_factory=dict)


def parse_worktree_porcelain(text: str) -> list[Worktree]:
    """Parse ``git worktree list --porcelain`` into ``Worktree`` records.

    The porcelain format is a sequence of records separated by blank
    lines. Each record starts with ``worktree <path>`` and may carry
    ``HEAD <sha>``, ``branch refs/heads/<name>``, ``detached``, and
    ``locked [<reason>]`` lines (any of which can be absent).

    We skip the bare-repo record (``worktree <path>\\nbare``) because
    cleaning the bare repo would nuke the whole checkout — that's the
    root container, not a deletable scratch worktree.
    """
    records: list[Worktree] = []
    current: dict[str, object] | None = None

    def flush() -> None:
        nonlocal current
        if current is None:
            return
        if current.get("bare"):
            current = None
            return
        path = current.get("path")
        if not isinstance(path, str):
            current = None
            return
        head_val = current.get("head")
        branch_val = current.get("branch")
        records.append(
            Worktree(
                path=path,
                head=head_val if isinstance(head_val, str) else None,
                branch=branch_val if isinstance(branch_val, str) else None,
                detached=bool(current.get("detached")),
                locked=bool(current.get("locked")),
            )
        )
        current = None

    for raw in text.splitlines():
        line = raw.rstrip()
        if not line:
            flush()
            continue
        if line.startswith("worktree "):
            flush()
            current = {"path": line[len("worktree ") :].strip()}
            continue
        if current is None:
            # Stray line before any "worktree " header — skip.
            continue
        if line.startswith("HEAD "):
            current["head"] = line[len("HEAD ") :].strip()
        elif line.startswith("branch "):
            ref = line[len("branch ") :].strip()
            short = ref[len("refs/heads/") :] if ref.startswith("refs/heads/") else ref
            current["branch"] = short
        elif line == "detached":
            current["detached"] = True
        elif line == "bare":
            current["bare"] = True
        elif line.startswith("locked") or line == "locked":
            current["locked"] = True
        # Other porcelain fields (prunable, etc.) ignored — they don't
        # change our stale decision.
    flush()
    return records


def _path_under_loop_prefix(worktree_path: str, repo_root: str) -> bool:
    """True iff ``worktree_path`` is inside ``<repo_root>/.worktrees/``.

    Both paths are realpath-resolved so a symlink can't smuggle a
    user-owned checkout past the prefix guard.
    """
    try:
        wt_real = os.path.realpath(worktree_path)
        prefix_real = os.path.realpath(os.path.join(repo_root, LOOP_WORKTREE_PREFIX))
    except OSError:
        return False
    # Ensure prefix ends with a separator so /home/foo/.worktreesX
    # doesn't sneak past a startswith on /home/foo/.worktrees.
    if not prefix_real.endswith(os.sep):
        prefix_real = prefix_real + os.sep
    return wt_real.startswith(prefix_real)


def _mtime_hours(path: str, *, now: float | None = None) -> float | None:
    """Return age in hours of the path's mtime, or None if it can't be read.

    We sample the directory mtime itself rather than walking children:
    a worktree that hasn't been written to recently is the stale one,
    and walking 20+ checkouts each iteration would be slow.
    """
    try:
        st = os.stat(path)
    except OSError:
        return None
    if now is None:
        now = time.time()
    return max(0.0, (now - st.st_mtime) / 3600.0)


def _git(args: list[str], *, cwd: str) -> subprocess.CompletedProcess:
    """Run ``git`` with the given args, capturing stdout/stderr as text."""
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )


def _parse_porcelain_status_paths(porcelain_text: str) -> list[str]:
    """Extract the path component from each `git status --porcelain=v1` line.

    Each line is ``XY <path>`` (possibly with a `-> renamed` suffix for
    rename entries). We return the FIRST path token only — for the
    "is this dirty" filter we don't care about the rename target.
    """
    paths: list[str] = []
    for raw in porcelain_text.splitlines():
        if not raw:
            continue
        # Status lines are ``XY <space> path``. After the two-char status
        # there's always a space. Strip the first 3 chars then split on
        # ``" -> "`` (rename) and keep the source side.
        if len(raw) < 3:
            continue
        body = raw[3:]
        if " -> " in body:
            body = body.split(" -> ", 1)[0]
        paths.append(body.strip())
    return paths


def _path_is_ignorable(path: str, ignore_paths: frozenset[str]) -> bool:
    """True if ``path`` (from a porcelain line) is in the ignore allowlist.

    Directory entries in the allowlist end with ``/``. We match against:
      - exact-equality (``.coverage``), or
      - first-segment-equality (``"./.venv/foo" startswith ".venv/"``).
    The first segment is everything up to the first ``/`` boundary.
    """
    if not path:
        return False
    for ignore in ignore_paths:
        if ignore.endswith("/"):
            # Directory entry — match if path's first segment is this dir.
            if path == ignore.rstrip("/"):
                return True
            if path.startswith(ignore):
                return True
        else:
            # Exact-match file.
            if path == ignore:
                return True
    return False


def _has_local_changes(
    worktree_path: str, *, ignore_paths: frozenset[str] = DEFAULT_IGNORE_PATHS
) -> bool:
    """True if the worktree has any uncommitted or untracked files NOT
    in the ``ignore_paths`` allowlist.

    The loop's worktrees universally show ``?? .venv/`` because each
    HEAD pins an older ``.gitignore`` that didn't list it — those are
    environment churn, not user work. By filtering known-noise paths,
    we avoid the trivial false-positive while still catching real
    untracked / modified source files.
    """
    res = _git(["status", "--porcelain=v1"], cwd=worktree_path)
    if res.returncode != 0:
        # Couldn't query status — treat as dirty to be safe.
        return True
    paths = _parse_porcelain_status_paths(res.stdout)
    real_changes = [p for p in paths if not _path_is_ignorable(p, ignore_paths)]
    return bool(real_changes)


def _is_ancestor(sha: str, *, master_ref: str, repo_root: str) -> bool:
    """True iff ``sha`` is reachable from ``master_ref``.

    ``git merge-base --is-ancestor A B`` exits 0 when A is an ancestor
    of B. This is true when the branch was either a fast-forward / merge
    commit (rare in simf — squash is the merge method), OR the worktree
    sat exactly on a master commit (no diverging work).

    GitHub squash-merge creates a NEW commit on master, so the original
    branch tip is NOT an ancestor of master post-squash. That blind spot
    is covered by ``_fetch_prs_by_head`` below — squash-merged worktrees
    are matched via their branch's merged PR instead.
    """
    res = _git(["merge-base", "--is-ancestor", sha, master_ref], cwd=repo_root)
    return res.returncode == 0


def _read_token(token_path: Path = DEFAULT_TOKEN_PATH) -> str | None:
    """Read the GitHub PAT or return None if not present.

    Returning None signals "skip the PR-merged fallback gracefully" —
    the script still works in ancestry-only mode for offline / no-PAT
    users. We do NOT raise here; an absent token is expected (e.g. CI).
    """
    if not token_path.exists():
        return None
    return token_path.read_text().strip() or None


def _http_get(url: str, token: str) -> object:
    req = urllib.request.Request(url)
    req.add_header("Authorization", f"token {token}")
    req.add_header("Accept", "application/vnd.github+json")
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _fetch_prs_by_head(token: str) -> dict[str, list[dict]]:
    """Group recent PRs by ``head.ref`` so we can look up branch-merge state.

    Mirror of the prune-script helper. We page through both open and
    closed PRs and return ``{head_ref: [pr, ...]}``. The caller picks
    the newest PR for each branch (largest number) and checks
    ``merged_at is not None``.
    """
    out: dict[str, list[dict]] = {}
    for state in ("open", "closed"):
        page = 1
        while True:
            url = f"{API_ROOT}/pulls?state={state}&per_page=100&page={page}"
            try:
                data = _http_get(url, token)
            except (urllib.error.HTTPError, urllib.error.URLError):
                # Network failure — degrade to ancestry-only.
                return out
            if not isinstance(data, list) or not data:
                break
            for pr in data:
                head = pr.get("head", {}).get("ref")
                if head:
                    out.setdefault(head, []).append(pr)
            if len(data) < 100:
                break
            page += 1
    return out


def branch_has_merged_pr(branch: str | None, prs_by_head: dict[str, list[dict]]) -> bool:
    """True if the latest PR matching ``branch`` was merged.

    Mirror of ``prune_merged_branches.classify_branch``'s newest-PR
    rule: pick the PR with the largest number and check ``merged_at``.
    Returns False on missing branch / no matching PR / open PR / closed-
    without-merge. None branch (detached) → False (callers should fall
    back to ancestry-only on detached worktrees).
    """
    if not branch:
        return False
    matching = prs_by_head.get(branch, [])
    if not matching:
        return False
    newest = max(matching, key=lambda p: p.get("number", 0))
    return newest.get("merged_at") is not None


def classify(
    worktree: Worktree,
    *,
    repo_root: str,
    current_worktree_path: str,
    master_ref: str,
    age_threshold_hours: float,
    now: float | None = None,
    is_ancestor_fn=None,
    branch_merged_fn=None,
    has_local_changes_fn=None,
    mtime_hours_fn=None,
) -> Classification:
    """Decide STALE vs KEEP for one worktree.

    The hooks (``is_ancestor_fn`` / ``branch_merged_fn`` /
    ``has_local_changes_fn`` / ``mtime_hours_fn``) exist so the tests
    can drive the classifier without touching real git state. The
    defaults call out to git / the GitHub API.

    Order of checks (short-circuit on first KEEP signal):
      1. Path must live under ``.worktrees/`` — anything else
         is the user's checkout, always KEEP.
      2. Not the current worktree (running iteration) — always KEEP.
      3. Filesystem mtime ≥ ``age_threshold_hours`` — recent worktrees
         are likely in-flight, KEEP until they age out.
      4. No local uncommitted / untracked changes (after applying the
         ignore-paths allowlist) — if ANY real changes exist, KEEP.
      5. Work is merged — EITHER ``HEAD`` is reachable from
         ``master_ref`` OR the worktree's branch has a merged PR
         (squash-merge case). If neither, KEEP — work might be
         unfinished or rejected.
    """
    if is_ancestor_fn is None:

        def is_ancestor_fn(sha: str) -> bool:
            return _is_ancestor(sha, master_ref=master_ref, repo_root=repo_root)

    if branch_merged_fn is None:

        def branch_merged_fn(_branch: str | None) -> bool:
            return False  # Default: no PR signal — rely on ancestry alone.

    if has_local_changes_fn is None:
        has_local_changes_fn = _has_local_changes
    if mtime_hours_fn is None:

        def mtime_hours_fn(p: str) -> float | None:
            return _mtime_hours(p, now=now)

    # 1. Path guard — only loop-managed worktrees are eligible.
    if not _path_under_loop_prefix(worktree.path, repo_root):
        return Classification(
            worktree=worktree,
            stale=False,
            reason="path outside .worktrees/ (protected)",
        )

    # 2. Never delete the worktree we're running from.
    try:
        same = os.path.realpath(worktree.path) == os.path.realpath(current_worktree_path)
    except OSError:
        same = False
    if same:
        return Classification(
            worktree=worktree,
            stale=False,
            reason="this is the current worktree (running iteration)",
        )

    # 3. Age gate.
    age = mtime_hours_fn(worktree.path)
    if age is None:
        return Classification(
            worktree=worktree,
            stale=False,
            reason="couldn't read mtime (skipping defensively)",
        )
    if age < age_threshold_hours:
        return Classification(
            worktree=worktree,
            stale=False,
            reason=f"too recent ({age:.1f}h < {age_threshold_hours:.1f}h threshold)",
            age_hours=age,
        )

    # 4. Local-changes gate.
    dirty = has_local_changes_fn(worktree.path)
    if dirty:
        return Classification(
            worktree=worktree,
            stale=False,
            reason="has uncommitted or untracked changes (refusing to delete)",
            age_hours=age,
            has_local_changes=True,
        )

    # 5. Merge gate — ancestry OR PR-merged. Either is sufficient
    # because squash-merge drops ancestry while still leaving the
    # branch's PR with ``merged_at != None``.
    if worktree.head is None:
        return Classification(
            worktree=worktree,
            stale=False,
            reason="no HEAD recorded (skipping defensively)",
            age_hours=age,
        )
    ancestor_merged = is_ancestor_fn(worktree.head)
    pr_merged = branch_merged_fn(worktree.branch)
    if not (ancestor_merged or pr_merged):
        return Classification(
            worktree=worktree,
            stale=False,
            reason=(
                f"HEAD {worktree.head[:8]} not reachable from {master_ref} "
                "and no merged PR for branch (work not merged — keeping)"
            ),
            age_hours=age,
            branch_merged=False,
        )

    via = []
    if ancestor_merged:
        via.append(f"ancestor of {master_ref}")
    if pr_merged:
        via.append(f"PR for {worktree.branch} merged")
    return Classification(
        worktree=worktree,
        stale=True,
        reason=f"merged ({'; '.join(via)}), age {age:.1f}h, clean tree",
        age_hours=age,
        branch_merged=True,
    )


def _list_worktrees(repo_root: str) -> list[Worktree]:
    res = _git(["worktree", "list", "--porcelain"], cwd=repo_root)
    if res.returncode != 0:
        raise RuntimeError(f"git worktree list failed: {res.stderr.strip()}")
    return parse_worktree_porcelain(res.stdout)


def _fetch_master(repo_root: str, *, master_ref: str) -> None:
    """Best-effort refresh of ``master_ref``. Network failures are non-fatal —
    the user might be offline; we still classify with whatever's local."""
    # Only refresh if master_ref points at a remote ref (e.g. origin/master).
    if "/" not in master_ref:
        return
    remote = master_ref.split("/", 1)[0]
    _git(["fetch", remote, "master"], cwd=repo_root)


def _remove_worktree(path: str, *, repo_root: str) -> tuple[bool, str]:
    """Unlock + remove one worktree. Returns (ok, message)."""
    unlock = _git(["worktree", "unlock", path], cwd=repo_root)
    # Unlock can fail benignly if the worktree wasn't locked — that's fine.
    if unlock.returncode != 0 and "not locked" not in (unlock.stderr or "").lower():
        # Surface real errors but keep going to the remove step — remove
        # itself may succeed without an unlock if git's state is funny.
        pass
    remove = _git(["worktree", "remove", "--force", path], cwd=repo_root)
    if remove.returncode != 0:
        return False, f"git worktree remove failed: {remove.stderr.strip()}"
    return True, "removed"


def _delete_branch(branch: str, *, repo_root: str) -> tuple[bool, str]:
    """Delete the local branch ref (``-D``, force, since work is merged)."""
    res = _git(["branch", "-D", branch], cwd=repo_root)
    if res.returncode != 0:
        return False, f"git branch -D failed: {res.stderr.strip()}"
    return True, "branch deleted"


def run(
    *,
    repo_root: str,
    current_worktree_path: str,
    master_ref: str,
    age_threshold_hours: float,
    delete: bool,
    fetch: bool = True,
    use_pr_merge_check: bool = True,
) -> list[Classification]:
    """Top-level entry. Returns the per-worktree classification list."""
    if fetch:
        _fetch_master(repo_root, master_ref=master_ref)

    prs_by_head: dict[str, list[dict]] = {}
    pr_check_status = "disabled"
    if use_pr_merge_check:
        token = _read_token()
        if token is None:
            pr_check_status = "skipped (no PAT at ~/.config/gh/token)"
        else:
            prs_by_head = _fetch_prs_by_head(token)
            pr_check_status = f"loaded {sum(len(v) for v in prs_by_head.values())} PRs"

    def branch_merged_fn(branch: str | None) -> bool:
        return branch_has_merged_pr(branch, prs_by_head)

    worktrees = _list_worktrees(repo_root)
    classifications = [
        classify(
            wt,
            repo_root=repo_root,
            current_worktree_path=current_worktree_path,
            master_ref=master_ref,
            age_threshold_hours=age_threshold_hours,
            branch_merged_fn=branch_merged_fn,
        )
        for wt in worktrees
    ]

    stale = [c for c in classifications if c.stale]
    kept = [c for c in classifications if not c.stale]

    print(f"# total worktrees: {len(classifications)}")
    print(f"# stale (would remove): {len(stale)}")
    print(f"# kept: {len(kept)}")
    print(f"# PR-merge check: {pr_check_status}\n")

    for c in classifications:
        tag = "REMOVE" if c.stale else "KEEP  "
        branch_or_detached = c.worktree.branch or ("(detached)" if c.worktree.detached else "(?)")
        print(f"  {tag}  {c.worktree.path}  [{branch_or_detached}]  {c.reason}")

    if not delete:
        print("\n(dry-run; pass --delete to actually remove the REMOVE entries)")
        return classifications

    print("\nRemoving stale worktrees...")
    for c in stale:
        ok, msg = _remove_worktree(c.worktree.path, repo_root=repo_root)
        status = "OK" if ok else f"ERROR ({msg})"
        print(f"  {c.worktree.path}: {status}")
        if not ok:
            continue
        # Best-effort branch ref cleanup for loop-pattern branches only.
        if c.worktree.branch and LOOP_BRANCH_PATTERN.match(c.worktree.branch):
            ok_b, msg_b = _delete_branch(c.worktree.branch, repo_root=repo_root)
            status_b = "OK" if ok_b else f"WARN ({msg_b})"
            print(f"    branch {c.worktree.branch}: {status_b}")
    return classifications


def _resolve_repo_root() -> str:
    """Find the top-level repo root, even when invoked from a worktree."""
    here = Path(__file__).resolve().parent.parent
    res = subprocess.run(
        ["git", "-C", str(here), "rev-parse", "--git-common-dir"],
        capture_output=True,
        text=True,
        check=False,
    )
    if res.returncode != 0:
        return str(here)
    common = Path(res.stdout.strip())
    if not common.is_absolute():
        common = (here / common).resolve()
    # `git-common-dir` points at the bare repo / .git directory. The repo
    # root is its parent (for the bare layout we have, it IS the parent).
    return str(common.parent if common.name == ".git" else common)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--age",
        type=float,
        default=4.0,
        help="Minimum mtime age in hours before a worktree is eligible (default: 4).",
    )
    parser.add_argument(
        "--master-ref",
        default="origin/master",
        help="Ref to test ancestry against (default: origin/master).",
    )
    parser.add_argument(
        "--delete",
        action="store_true",
        help="Actually unlock + remove stale worktrees (default: dry-run).",
    )
    parser.add_argument(
        "--no-fetch",
        action="store_true",
        help="Skip the implicit `git fetch` before classifying.",
    )
    parser.add_argument(
        "--no-pr-check",
        action="store_true",
        help=(
            "Skip the GitHub-PR-merged fallback (ancestry-only). "
            "Default ON when ~/.config/gh/token is present."
        ),
    )
    args = parser.parse_args(argv)

    repo_root = _resolve_repo_root()
    current = os.getcwd()
    run(
        repo_root=repo_root,
        current_worktree_path=current,
        master_ref=args.master_ref,
        age_threshold_hours=args.age,
        delete=args.delete,
        fetch=not args.no_fetch,
        use_pr_merge_check=not args.no_pr_check,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
