#!/usr/bin/env python3
"""Regenerate `src/simf/data/realms.yaml` from the Blizzard Realm Index.

The realm list is bundled (not fetched at runtime) so the name-lookup form
renders instantly and works for the majority of users who have no Blizzard
API creds. Realm lists change rarely (new realms, connected-realm renames),
so a manual regen is fine:

    .venv/bin/python scripts/fetch_realms.py

Requires Blizzard creds (`~/.simf/blizzard.yaml`) for the client-credentials
token. Stores the *real* Blizzard slug per realm — naive slugification of the
display name is wrong for special-char realms (e.g. `Drak'Tharon` →
`draktharon`, not `drak'tharon`), which would 404 on lookup.

Test/instance realms (`AU2A3-INST`, `EU1A1-INST`, `RDB US`, …) are dropped:
real realm names are title-case proper nouns and always contain a lowercase
letter, whereas the internal realms are ALL-CAPS codes.
"""

from __future__ import annotations

import datetime
from pathlib import Path

import yaml

from simf.io.armory import _fetch_json
from simf.io.item_db import _get_token

REGIONS = ["us", "eu", "kr", "tw"]

# Substrings that mark Blizzard-internal / management realms (not playable).
# ALL-CAPS code realms (EU1A1-INST, RDB US) are caught separately by the
# "has a lowercase letter" test in _is_real_realm.
_INTERNAL_MARKERS = ("account realm", "auxiliary", "arena pass", "gmsupport")
OUT = Path(__file__).resolve().parent.parent / "src" / "simf" / "data" / "realms.yaml"


def _is_real_realm(name: str) -> bool:
    """Real realms are title-case proper nouns (have a lowercase letter);
    internal/test realms are ALL-CAPS codes like `EU1A1-INST` / `RDB US`, or
    `zzz_`-prefixed staging entries like `zzz_RDB EU`.

    NB: filter on these specific markers, NOT an "inst"/"rdb" substring —
    "Sinstralis" is a real EU realm an "inst" filter would drop. (Of the
    digit-bearing names, only "Area 52" is a real realm.)
    """
    low = name.lower()
    if low.startswith("zzz") or any(m in low for m in _INTERNAL_MARKERS):
        return False
    return any(c.islower() for c in name)


def fetch_region(region: str) -> list[list[str]]:
    token = _get_token(region)
    if not token:
        raise SystemExit(f"No Blizzard token for {region} — check ~/.simf/blizzard.yaml")
    data = _fetch_json(
        f"https://{region}.api.blizzard.com/data/wow/realm/index",
        token,
        f"dynamic-{region}",
        region,
    )
    if not data or "realms" not in data:
        raise SystemExit(f"Realm index fetch failed for {region}: {data!r}")
    pairs = sorted(
        ([r["name"], r["slug"]] for r in data["realms"] if _is_real_realm(r["name"])),
        key=lambda p: p[0].casefold(),
    )
    return pairs


def main() -> int:
    realms = {region: fetch_region(region) for region in REGIONS}
    header = (
        "# Auto-generated by scripts/fetch_realms.py from the Blizzard Realm Index.\n"
        f"# Generated {datetime.date.today().isoformat()}. Regenerate when realms are\n"
        "# added/renamed/connected. Each entry is [display name, blizzard slug];\n"
        "# the slug is passed to the lookup (naive name-slugification breaks\n"
        "# special-char realms like Drak'Tharon -> draktharon).\n"
    )
    body = yaml.safe_dump(realms, sort_keys=False, allow_unicode=True, width=1000)
    OUT.write_text(header + body)
    counts = ", ".join(f"{r}={len(realms[r])}" for r in REGIONS)
    print(f"Wrote {OUT} ({counts})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
